modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId="space_simulation"
version="1.0.0"
displayName="Space Simulation"
authors="XYccWA"
description=''''''

[[dependencies.space_simulation]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.space_simulation]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.space_simulation]]
modId="valkyrienskies"
mandatory=true
versionRange="[2.4,)"    # 对应2.4.10版本
ordering="AFTER"
side="BOTH"